apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: conversao
        image: abcs89/conversao-temperatura
        ports:
        - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
